using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace BcsSharp.SourceGenerator;

[Generator]
public sealed class BcsFormatterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all types marked with [BcsStruct]
        var bcsStructTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "BcsSharp.Core.Attributes.BcsStructAttribute",
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => GetBcsStructInfo(ctx))
            .Where(static m => m is not null)
            .Collect();

        // Generate formatters and resolver
        context.RegisterSourceOutput(bcsStructTypes, static (spc, types) => Execute(spc, types!));
    }

    private static BcsStructInfo? GetBcsStructInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetNode is not TypeDeclarationSyntax typeDeclaration)
            return null;

        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        // Get all fields/properties marked with [BcsField]
        var fields = new List<BcsFieldInfo>();

        // Process fields
        foreach (var field in typeSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            var bcsFieldAttr = field.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BcsSharp.Core.Attributes.BcsFieldAttribute");

            if (bcsFieldAttr != null)
            {
                var order = bcsFieldAttr.ConstructorArguments.FirstOrDefault().Value as int? ?? 0;
                fields.Add(new BcsFieldInfo(field.Name, field.Type.ToDisplayString(), field.Type, order, true));
            }
        }

        // Process properties
        foreach (var property in typeSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var bcsFieldAttr = property.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BcsSharp.Core.Attributes.BcsFieldAttribute");

            if (bcsFieldAttr != null)
            {
                var order = bcsFieldAttr.ConstructorArguments.FirstOrDefault().Value as int? ?? 0;
                fields.Add(new BcsFieldInfo(property.Name, property.Type.ToDisplayString(), property.Type, order, false));
            }
        }

        if (fields.Count == 0)
            return null;

        // Sort by order
        fields.Sort((a, b) => a.Order.CompareTo(b.Order));

        return new BcsStructInfo(
            typeSymbol.ToDisplayString(),
            typeSymbol.Name,
            typeSymbol.ContainingNamespace?.ToDisplayString() ?? "",
            fields,
            typeSymbol.IsValueType,
            typeSymbol
        );
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<BcsStructInfo> types)
    {
        if (types.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        var allTypes = new Dictionary<string, BcsStructInfo>();

        // Build dictionary of all known types using fully qualified name
        foreach (var type in types)
        {
            var fullyQualifiedName = type.TypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            allTypes[fullyQualifiedName] = type;
        }

        // Generate individual formatters
        foreach (var type in types)
        {
            sb.Clear();
            GenerateFormatter(sb, type, allTypes);
            // Use full type name to avoid duplicates when types have same name in different namespaces
            var hintName = type.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter.g.cs";
            context.AddSource(hintName, sb.ToString());
        }

        // Generate resolver
        sb.Clear();
        GenerateResolver(sb, types);
        context.AddSource("BcsSourceGeneratorResolver.g.cs", sb.ToString());
    }

    private static void GenerateFormatter(StringBuilder sb, BcsStructInfo type, Dictionary<string, BcsStructInfo> allTypes)
    {
        var namespaceName = string.IsNullOrEmpty(type.Namespace) ? "BcsSharp.Generated" : $"{type.Namespace}.Generated";

        sb.AppendLine($@"
// <auto-generated />
#nullable enable

using BcsSharp.Core;
using System.Runtime.CompilerServices;

namespace {namespaceName};
");

        // Use sanitized type name to avoid conflicts
        var formatterClassName = type.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";

        sb.AppendLine($@"
public sealed class {formatterClassName} : IBcsFormatter<{type.FullTypeName}>
{{
    public static readonly {formatterClassName} Instance = new();
    public Type TargetType => typeof({type.FullTypeName});

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Serialize(ref BcsWriter writer, {type.FullTypeName} value)
    {{
");


        foreach (var field in type.Fields)
        {
            var writeCall = GetDirectWriteCall(field, allTypes);
            sb.AppendLine($"        // {field.Name}");
            sb.AppendLine($"        {writeCall}");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Deserialize method
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public {type.FullTypeName} Deserialize(ref BcsReader reader)");
        sb.AppendLine("    {");

        if (type.IsValueType)
        {
            // For structs, use object initializer
            sb.AppendLine($"        return new {type.FullTypeName}");
            sb.AppendLine("        {");
            for (int i = 0; i < type.Fields.Count; i++)
            {
                var field = type.Fields[i];
                var comma = i < type.Fields.Count - 1 ? "," : "";
                var readCall = GetDirectReadCall(field, allTypes);
                sb.AppendLine($"            // {field.Name}");
                sb.AppendLine($"            {field.Name} = {readCall}{comma}");
            }
            sb.AppendLine("        };");
        }
        else
        {
            // For classes, create instance and set properties
            sb.AppendLine($"        var result = new {type.FullTypeName}();");
            foreach (var field in type.Fields)
            {
                var readCall = GetDirectReadCall(field, allTypes);
                sb.AppendLine($"        // {field.Name}");
                sb.AppendLine($"        result.{field.Name} = {readCall};");
            }
            sb.AppendLine("        return result;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // GetSerializedSize method - simplified to return null for now
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public int? GetSerializedSize({type.FullTypeName} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        return null; // Size calculation not implemented yet");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Add helper methods for primitive arrays if needed
        if (type.Fields.Any(f => GetFullyQualifiedTypeName(f.TypeSymbol).EndsWith("[]") && IsPrimitiveArrayType(GetFullyQualifiedTypeName(f.TypeSymbol))))
        {
            GeneratePrimitiveArrayHelpers(sb);
        }

        // Add helper methods for nullable arrays if needed
        var nullableArrayFields = type.Fields.Where(f => IsNullableArrayType(GetFullyQualifiedTypeName(f.TypeSymbol))).ToList();
        if (nullableArrayFields.Any())
        {
            GenerateNullableArrayHelpers(sb, nullableArrayFields);
        }

        // Add helper methods for enums if needed
        var enumFields = type.Fields.Where(f => f.TypeSymbol.TypeKind == TypeKind.Enum).ToList();
        if (enumFields.Any())
        {
            GenerateEnumHelpers(sb, enumFields);
        }

        sb.AppendLine("}");
    }

    private static string GetFullyQualifiedTypeName(ITypeSymbol typeSymbol)
    {
        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string GetDirectWriteCall(BcsFieldInfo field, Dictionary<string, BcsStructInfo> allTypes)
    {
        var fullyQualifiedTypeName = GetFullyQualifiedTypeName(field.TypeSymbol);

        // Handle nullable primitive types first
        if (IsNullableType(fullyQualifiedTypeName, out var underlyingType))
        {
            return GetNullableWriteCall(field, underlyingType);
        }

        // Handle C-style enums - serialize by underlying integer value
        if (field.TypeSymbol.TypeKind == TypeKind.Enum)
        {
            return GetEnumWriteCall(field);
        }

        // Handle strings - always use WriteString regardless of nullable annotation
        if (fullyQualifiedTypeName == "string" || fullyQualifiedTypeName == "global::System.String" ||
            fullyQualifiedTypeName == "string?" || fullyQualifiedTypeName == "global::System.String?")
        {
            return $"writer.WriteString(value.{field.Name});";
        }

        return fullyQualifiedTypeName switch
        {
            // Primitive types - direct BcsWriter calls (handle both simple and fully qualified names)
            "byte" or "global::System.Byte" => $"writer.Write(value.{field.Name});",
            "sbyte" or "global::System.SByte" => $"writer.Write(value.{field.Name});",
            "ushort" or "global::System.UInt16" => $"writer.Write(value.{field.Name});",
            "short" or "global::System.Int16" => $"writer.Write(value.{field.Name});",
            "uint" or "global::System.UInt32" => $"writer.Write(value.{field.Name});",
            "int" or "global::System.Int32" => $"writer.Write(value.{field.Name});",
            "ulong" or "global::System.UInt64" => $"writer.Write(value.{field.Name});",
            "long" or "global::System.Int64" => $"writer.Write(value.{field.Name});",
            "UInt128" or "global::System.UInt128" => $"writer.Write(value.{field.Name});",
            "Int128" or "global::System.Int128" => $"writer.Write(value.{field.Name});",
            "global::Nethermind.Int256.UInt256" => $"writer.Write(value.{field.Name});",
            "bool" or "global::System.Boolean" => $"writer.WriteBool(value.{field.Name});",


            // Arrays of primitives - check if we can use vectorized operations
            "bool[]" or "global::System.Boolean[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "byte[]" or "global::System.Byte[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "sbyte[]" or "global::System.SByte[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "ushort[]" or "global::System.UInt16[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "short[]" or "global::System.Int16[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "uint[]" or "global::System.UInt32[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "int[]" or "global::System.Int32[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "ulong[]" or "global::System.UInt64[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "long[]" or "global::System.Int64[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "UInt128[]" or "global::System.UInt128[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "Int128[]" or "global::System.Int128[]" => GetFormatterPrimitiveArrayWriteCall(field),
            "global::Nethermind.Int256.UInt256[]" => GetFormatterPrimitiveArrayWriteCall(field),

            // Arrays of nullable primitives - custom handling
            "byte?[]" or "global::System.Byte?[]" => GetNullableArrayWriteCall(field, "byte"),
            "sbyte?[]" or "global::System.SByte?[]" => GetNullableArrayWriteCall(field, "sbyte"),
            "ushort?[]" or "global::System.UInt16?[]" => GetNullableArrayWriteCall(field, "ushort"),
            "short?[]" or "global::System.Int16?[]" => GetNullableArrayWriteCall(field, "short"),
            "uint?[]" or "global::System.UInt32?[]" => GetNullableArrayWriteCall(field, "uint"),
            "int?[]" or "global::System.Int32?[]" => GetNullableArrayWriteCall(field, "int"),
            "ulong?[]" or "global::System.UInt64?[]" => GetNullableArrayWriteCall(field, "ulong"),
            "long?[]" or "global::System.Int64?[]" => GetNullableArrayWriteCall(field, "long"),
            "UInt128?[]" or "global::System.UInt128?[]" => GetNullableArrayWriteCall(field, "UInt128"),
            "Int128?[]" or "global::System.Int128?[]" => GetNullableArrayWriteCall(field, "Int128"),
            "bool?[]" or "global::System.Boolean?[]" => GetNullableArrayWriteCall(field, "bool"),

            // Check if it's a OneOf<None, T> type where T is a known BcsStruct
            _ when IsOneOfNoneType(field.TypeSymbol, allTypes, out var innerTypeInfo) => GetOneOfFormatterWriteCall(field, innerTypeInfo!),

            // Check if it's a tuple type
            _ when IsTupleType(fullyQualifiedTypeName, out var tupleTypes) => GetTupleWriteCall(field, tupleTypes, allTypes),

            // Check if it's a known BcsStruct type - use dedicated formatter
            _ when allTypes.ContainsKey(GetFullyQualifiedTypeName(field.TypeSymbol)) => GetFormatterWriteCall(field, allTypes[GetFullyQualifiedTypeName(field.TypeSymbol)]),

            // Fall back to BcsSerializer for unknown complex types
            _ => $"BcsSerializer.Serialize(ref writer, value.{field.Name});"
        };
    }

    private static string GetFormatterPrimitiveArrayWriteCall(BcsFieldInfo field)
    {
        var fullyQualifiedTypeName = GetFullyQualifiedTypeName(field.TypeSymbol);
        // Extract the element type by removing the [] suffix and global:: prefix for primitive types
        var elementType = fullyQualifiedTypeName.Replace("[]", "").Replace("global::System.", "").Replace("global::", "");
        return $"writer.WriteULEB((uint)value.{field.Name}.Length); writer.WritePrimitiveArray<{elementType}>(value.{field.Name});";
    }

    private static string GetNullableArrayWriteCall(BcsFieldInfo field, string elementType)
    {
        var nullableWriteCall = GetNullableElementWriteCall(elementType);

        return $@"if (value.{field.Name} == null) {{ writer.WriteULEB(0u); }} else {{ writer.WriteULEB((uint)value.{field.Name}.Length); foreach (var item in value.{field.Name}) {{ {nullableWriteCall} }} }}";
    }

    private static string GetNullableElementWriteCall(string elementType)
    {
        return elementType switch
        {
            "byte" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "sbyte" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "ushort" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "short" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "uint" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "int" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "ulong" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "long" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "UInt128" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "Int128" => "if (item.HasValue) { writer.Write((byte)1); writer.Write(item.Value); } else { writer.Write((byte)0); }",
            "bool" => "if (item.HasValue) { writer.Write((byte)1); writer.WriteBool(item.Value); } else { writer.Write((byte)0); }",
            _ => "if (item.HasValue) { writer.Write((byte)1); BcsSerializer.Serialize(ref writer, item.Value); } else { writer.Write((byte)0); }"
        };
    }

    private static string GetNullableArrayReadCall(BcsFieldInfo field, string elementType)
    {
        var nullableReadCall = GetNullableElementReadCall(elementType);

        return $@"ReadNullableArray_{elementType}(ref reader)";
    }

    private static string GetNullableElementReadCall(string elementType)
    {
        return elementType switch
        {
            "byte" => "reader.Read8() == 0 ? null : reader.Read8()",
            "sbyte" => "reader.Read8() == 0 ? null : reader.ReadI8()",
            "ushort" => "reader.Read8() == 0 ? null : reader.Read16()",
            "short" => "reader.Read8() == 0 ? null : reader.ReadI16()",
            "uint" => "reader.Read8() == 0 ? null : reader.Read32()",
            "int" => "reader.Read8() == 0 ? null : reader.ReadI32()",
            "ulong" => "reader.Read8() == 0 ? null : reader.Read64()",
            "long" => "reader.Read8() == 0 ? null : reader.ReadI64()",
            "UInt128" => "reader.Read8() == 0 ? null : reader.Read128()",
            "Int128" => "reader.Read8() == 0 ? null : reader.ReadI128()",
            "bool" => "reader.Read8() == 0 ? null : reader.ReadBool()",
            _ => $"reader.Read8() == 0 ? null : BcsSerializer.Deserialize<{elementType}>(ref reader)"
        };
    }

    private static string GetFormatterWriteCall(BcsFieldInfo field, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";
        return $"{namespaceName}.{formatterClassName}.Instance.Serialize(ref writer, value.{field.Name});";
    }

    private static string GetFormatterReadCall(BcsFieldInfo field, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";
        return $"{namespaceName}.{formatterClassName}.Instance.Deserialize(ref reader)";
    }

    private static string GetFormatterSizeCall(BcsFieldInfo field, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";
        return $"{namespaceName}.{formatterClassName}.Instance.GetSerializedSize(value.{field.Name})";
    }

    private static bool IsOneOfNoneType(ITypeSymbol typeSymbol, Dictionary<string, BcsStructInfo> allTypes, out BcsStructInfo? innerTypeInfo)
    {
        innerTypeInfo = null;

        // Check if it's a generic OneOf type
        if (typeSymbol is INamedTypeSymbol namedType &&
            namedType.IsGenericType &&
            namedType.TypeArguments.Length == 2)
        {
            var typeName = namedType.ToDisplayString();

            // Check if it contains OneOf and None patterns
            if (typeName.Contains("OneOf") && typeName.Contains("None"))
            {
                // Find the non-None type argument
                foreach (var typeArg in namedType.TypeArguments)
                {
                    var typeArgDisplay = typeArg.ToDisplayString();
                    if (!typeArgDisplay.Contains("None"))
                    {
                        var fullyQualifiedName = GetFullyQualifiedTypeName(typeArg);
                        if (allTypes.ContainsKey(fullyQualifiedName))
                        {
                            innerTypeInfo = allTypes[fullyQualifiedName];
                            return true;
                        }
                    }
                }
            }
        }

        return false;
    }

    private static bool IsNullableType(string typeName, out string underlyingType)
    {
        underlyingType = "";

        // Handle Nullable<T> pattern, but exclude string? since strings are reference types
        if (typeName.EndsWith("?") && typeName != "string?" && typeName != "global::System.String?")
        {
            underlyingType = typeName.Substring(0, typeName.Length - 1);
            return true;
        }

        // Handle System.Nullable<T> pattern
        if (typeName.StartsWith("System.Nullable<") && typeName.EndsWith(">"))
        {
            underlyingType = typeName.Substring("System.Nullable<".Length, typeName.Length - "System.Nullable<".Length - 1);
            return true;
        }

        // Handle global::System.Nullable<T> pattern
        if (typeName.StartsWith("global::System.Nullable<") && typeName.EndsWith(">"))
        {
            underlyingType = typeName.Substring("global::System.Nullable<".Length, typeName.Length - "global::System.Nullable<".Length - 1);
            return true;
        }

        return false;
    }

    private static string GetNullableWriteCall(BcsFieldInfo field, string underlyingType)
    {
        var underlyingWriteCall = underlyingType switch
        {
            "byte" or "global::System.Byte" => $"writer.Write(value.{field.Name}.Value);",
            "sbyte" or "global::System.SByte" => $"writer.Write(value.{field.Name}.Value);",
            "ushort" or "global::System.UInt16" => $"writer.Write(value.{field.Name}.Value);",
            "short" or "global::System.Int16" => $"writer.Write(value.{field.Name}.Value);",
            "uint" or "global::System.UInt32" => $"writer.Write(value.{field.Name}.Value);",
            "int" or "global::System.Int32" => $"writer.Write(value.{field.Name}.Value);",
            "ulong" or "global::System.UInt64" => $"writer.Write(value.{field.Name}.Value);",
            "long" or "global::System.Int64" => $"writer.Write(value.{field.Name}.Value);",
            "UInt128" or "System.UInt128" or "global::System.UInt128" => $"writer.Write(value.{field.Name}.Value);",
            "Int128" or "System.Int128" or "global::System.Int128" => $"writer.Write(value.{field.Name}.Value);",
            "bool" or "global::System.Boolean" => $"writer.WriteBool(value.{field.Name}.Value);",
            _ => $"BcsSerializer.Serialize(ref writer, value.{field.Name}.Value);"
        };

        return $"if (value.{field.Name}.HasValue) {{ writer.Write((byte)1); {underlyingWriteCall} }} else {{ writer.Write((byte)0); }}";
    }

    private static string GetNullableReadCall(BcsFieldInfo field, string underlyingType)
    {
        var underlyingReadCall = underlyingType switch
        {
            "byte" or "global::System.Byte" => "reader.Read8()",
            "sbyte" or "global::System.SByte" => "reader.ReadI8()",
            "ushort" or "global::System.UInt16" => "reader.Read16()",
            "short" or "global::System.Int16" => "reader.ReadI16()",
            "uint" or "global::System.UInt32" => "reader.Read32()",
            "int" or "global::System.Int32" => "reader.ReadI32()",
            "ulong" or "global::System.UInt64" => "reader.Read64()",
            "long" or "global::System.Int64" => "reader.ReadI64()",
            "UInt128" or "System.UInt128" or "global::System.UInt128" => "reader.Read128()",
            "Int128" or "System.Int128" or "global::System.Int128" => "reader.ReadI128()",
            "bool" or "global::System.Boolean" => "reader.ReadBool()",
            _ => $"BcsSerializer.Deserialize<{underlyingType}>(ref reader)"
        };

        return $"reader.Read8() == 0 ? null : {underlyingReadCall}";
    }

    private static string GetEnumWriteCall(BcsFieldInfo field)
    {
        if (field.TypeSymbol is not INamedTypeSymbol enumSymbol)
        {
            // Fallback for unknown enum types
            return $"BcsSerializer.Serialize(ref writer, value.{field.Name});";
        }

        var enumTypeName = GetFullyQualifiedTypeName(field.TypeSymbol);

        // BCS C-style enum serialization: Use ordinal position (index) within enum definition
        // This ensures consistent serialization regardless of actual enum values
        return $"WriteEnumOrdinal_{GetEnumHelperSuffix(enumTypeName)}(ref writer, value.{field.Name});";
    }

    private static string GetEnumReadCall(BcsFieldInfo field)
    {
        if (field.TypeSymbol is not INamedTypeSymbol enumSymbol)
        {
            // Fallback for unknown enum types
            return $"BcsSerializer.Deserialize<{GetFullyQualifiedTypeName(field.TypeSymbol)}>(ref reader)";
        }

        var enumTypeName = GetFullyQualifiedTypeName(field.TypeSymbol);

        // BCS C-style enum deserialization: Read ordinal position and convert to enum value
        return $"ReadEnumOrdinal_{GetEnumHelperSuffix(enumTypeName)}(ref reader)";
    }

    private static string GetEnumHelperSuffix(string enumTypeName)
    {
        // Create a safe suffix for method names by replacing problematic characters
        return enumTypeName.Replace(".", "_").Replace("::", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_");
    }

    private static bool IsTupleType(string typeName, out string[] tupleTypes)
    {
        tupleTypes = [];

        // Handle ValueTuple<T1, T2, ...> pattern
        if (typeName.StartsWith("(") && typeName.EndsWith(")"))
        {
            // Extract tuple elements from (T1, T2, ...)
            var content = typeName.Substring(1, typeName.Length - 2);
            tupleTypes = content.Split(',').Select(t => t.Trim()).ToArray();
            return tupleTypes.Length >= 2;
        }

        // Handle System.ValueTuple<T1, T2, ...> pattern
        if (typeName.StartsWith("System.ValueTuple<") && typeName.EndsWith(">"))
        {
            var content = typeName.Substring("System.ValueTuple<".Length, typeName.Length - "System.ValueTuple<".Length - 1);
            tupleTypes = content.Split(',').Select(t => t.Trim()).ToArray();
            return tupleTypes.Length >= 2;
        }

        return false;
    }

    private static string GetTupleWriteCall(BcsFieldInfo field, string[] tupleTypes, Dictionary<string, BcsStructInfo> allTypes)
    {
        var writeStatements = new List<string>();

        for (int i = 0; i < tupleTypes.Length; i++)
        {
            var itemAccess = $"value.{field.Name}.Item{i + 1}";
            var writeCall = GetTypeWriteCall(tupleTypes[i], itemAccess, allTypes);
            writeStatements.Add(writeCall);
        }

        return string.Join(" ", writeStatements);
    }

    private static string GetTupleReadCall(BcsFieldInfo field, string[] tupleTypes, Dictionary<string, BcsStructInfo> allTypes)
    {
        var readExpressions = new List<string>();

        for (int i = 0; i < tupleTypes.Length; i++)
        {
            var readCall = GetTypeReadCall(tupleTypes[i], allTypes);
            readExpressions.Add(readCall);
        }

        return $"({string.Join(", ", readExpressions)})";
    }

    private static string GetTypeWriteCall(string typeName, string valueExpression, Dictionary<string, BcsStructInfo> allTypes)
    {
        return typeName switch
        {
            // Primitive types (handle both simple and fully qualified names)
            "byte" or "global::System.Byte" => $"writer.Write({valueExpression});",
            "sbyte" or "global::System.SByte" => $"writer.Write({valueExpression});",
            "ushort" or "global::System.UInt16" => $"writer.Write({valueExpression});",
            "short" or "global::System.Int16" => $"writer.Write({valueExpression});",
            "uint" or "global::System.UInt32" => $"writer.Write({valueExpression});",
            "int" or "global::System.Int32" => $"writer.Write({valueExpression});",
            "ulong" or "global::System.UInt64" => $"writer.Write({valueExpression});",
            "long" or "global::System.Int64" => $"writer.Write({valueExpression});",
            "bool" or "global::System.Boolean" => $"writer.WriteBool({valueExpression});",
            "string" or "global::System.String" => $"writer.WriteString({valueExpression});",
            "string?" or "global::System.String?" => $"if ({valueExpression} == null) {{ writer.Write((byte)0); }} else {{ writer.Write((byte)1); writer.WriteString({valueExpression}); }}",

            // Check if it's a known BcsStruct type
            _ when allTypes.ContainsKey(typeName) => GetFormatterWriteCallForExpression(typeName, valueExpression, allTypes[typeName]),

            // Fall back to BcsSerializer
            _ => $"BcsSerializer.Serialize(ref writer, {valueExpression});"
        };
    }

    private static string GetTypeReadCall(string typeName, Dictionary<string, BcsStructInfo> allTypes)
    {
        return typeName switch
        {
            // Primitive types (handle both simple and fully qualified names)
            "byte" or "global::System.Byte" => "reader.Read8()",
            "sbyte" or "global::System.SByte" => "reader.ReadI8()",
            "ushort" or "global::System.UInt16" => "reader.Read16()",
            "short" or "global::System.Int16" => "reader.ReadI16()",
            "uint" or "global::System.UInt32" => "reader.Read32()",
            "int" or "global::System.Int32" => "reader.ReadI32()",
            "ulong" or "global::System.UInt64" => "reader.Read64()",
            "long" or "global::System.Int64" => "reader.ReadI64()",
            "bool" or "global::System.Boolean" => "reader.ReadBool()",
            "string" or "global::System.String" => "reader.ReadString()",
            "string?" or "global::System.String?" => "reader.Read8() == 0 ? null : reader.ReadString()",

            // Check if it's a known BcsStruct type
            _ when allTypes.ContainsKey(typeName) => GetFormatterReadCallForType(typeName, allTypes[typeName]),

            // Fall back to BcsSerializer
            _ => $"BcsSerializer.Deserialize<{typeName}>(ref reader)"
        };
    }

    private static string GetFormatterWriteCallForExpression(string typeName, string valueExpression, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";
        return $"{namespaceName}.{formatterClassName}.Instance.Serialize(ref writer, {valueExpression});";
    }

    private static string GetFormatterReadCallForType(string typeName, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";
        return $"{namespaceName}.{formatterClassName}.Instance.Deserialize(ref reader)";
    }

    private static string GetOneOfFormatterWriteCall(BcsFieldInfo field, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";

        return $"if (value.{field.Name}.IsT0) {{ writer.Write((byte)0); }} else if (value.{field.Name}.IsT1) {{ writer.Write((byte)1); {namespaceName}.{formatterClassName}.Instance.Serialize(ref writer, value.{field.Name}.AsT1); }}";
    }

    private static string GetOneOfFormatterReadCall(BcsFieldInfo field, BcsStructInfo targetType)
    {
        var formatterClassName = targetType.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
        var namespaceName = string.IsNullOrEmpty(targetType.Namespace) ? "BcsSharp.Generated" : $"{targetType.Namespace}.Generated";

        return $"reader.Read8() == 0 ? new OneOf.Types.None() : {namespaceName}.{formatterClassName}.Instance.Deserialize(ref reader)";
    }

    private static string GetDirectReadCall(BcsFieldInfo field, Dictionary<string, BcsStructInfo> allTypes)
    {
        var fullyQualifiedTypeName = GetFullyQualifiedTypeName(field.TypeSymbol);

        // Handle nullable primitive types first
        if (IsNullableType(fullyQualifiedTypeName, out var underlyingType))
        {
            return GetNullableReadCall(field, underlyingType);
        }

        // Handle C-style enums - deserialize from underlying integer value
        if (field.TypeSymbol.TypeKind == TypeKind.Enum)
        {
            return GetEnumReadCall(field);
        }

        // Handle strings - always use ReadString regardless of nullable annotation
        if (fullyQualifiedTypeName == "string" || fullyQualifiedTypeName == "global::System.String" ||
            fullyQualifiedTypeName == "string?" || fullyQualifiedTypeName == "global::System.String?")
        {
            return "reader.ReadString()";
        }

        return fullyQualifiedTypeName switch
        {
            // Primitive types - direct BcsReader calls (handle both simple and fully qualified names)
            "byte" or "global::System.Byte" => "reader.Read8()",
            "sbyte" or "global::System.SByte" => "reader.ReadI8()",
            "ushort" or "global::System.UInt16" => "reader.Read16()",
            "short" or "global::System.Int16" => "reader.ReadI16()",
            "uint" or "global::System.UInt32" => "reader.Read32()",
            "int" or "global::System.Int32" => "reader.ReadI32()",
            "ulong" or "global::System.UInt64" => "reader.Read64()",
            "long" or "global::System.Int64" => "reader.ReadI64()",
            "UInt128" or "global::System.UInt128" => "reader.Read128()",
            "Int128" or "global::System.Int128" => "reader.ReadI128()",
            "global::Nethermind.Int256.UInt256" => "reader.Read256()",
            "bool" or "global::System.Boolean" => "reader.ReadBool()",

            // Arrays of primitives - vectorized read
            "bool[]" or "global::System.Boolean[]" => "ReadPrimitiveArray<bool>(ref reader)",
            "byte[]" or "global::System.Byte[]" => "reader.ReadBytes((int)reader.ReadULEB32())",
            "sbyte[]" or "global::System.SByte[]" => "ReadPrimitiveArray<sbyte>(ref reader)",
            "ushort[]" or "global::System.UInt16[]" => "ReadPrimitiveArray<ushort>(ref reader)",
            "short[]" or "global::System.Int16[]" => "ReadPrimitiveArray<short>(ref reader)",
            "uint[]" or "global::System.UInt32[]" => "ReadPrimitiveArray<uint>(ref reader)",
            "int[]" or "global::System.Int32[]" => "ReadPrimitiveArray<int>(ref reader)",
            "ulong[]" or "global::System.UInt64[]" => "ReadPrimitiveArray<ulong>(ref reader)",
            "long[]" or "global::System.Int64[]" => "ReadPrimitiveArray<long>(ref reader)",
            "UInt128[]" or "global::System.UInt128[]" => "ReadPrimitiveArray<System.UInt128>(ref reader)",
            "Int128[]" or "global::System.Int128[]" => "ReadPrimitiveArray<System.Int128>(ref reader)",
            "global::Nethermind.Int256.UInt256[]" => "ReadPrimitiveArray<Nethermind.Int256.UInt256>(ref reader)",

            // Arrays of nullable primitives - custom handling
            "byte?[]" or "global::System.Byte?[]" => GetNullableArrayReadCall(field, "byte"),
            "sbyte?[]" or "global::System.SByte?[]" => GetNullableArrayReadCall(field, "sbyte"),
            "ushort?[]" or "global::System.UInt16?[]" => GetNullableArrayReadCall(field, "ushort"),
            "short?[]" or "global::System.Int16?[]" => GetNullableArrayReadCall(field, "short"),
            "uint?[]" or "global::System.UInt32?[]" => GetNullableArrayReadCall(field, "uint"),
            "int?[]" or "global::System.Int32?[]" => GetNullableArrayReadCall(field, "int"),
            "ulong?[]" or "global::System.UInt64?[]" => GetNullableArrayReadCall(field, "ulong"),
            "long?[]" or "global::System.Int64?[]" => GetNullableArrayReadCall(field, "long"),
            "UInt128?[]" or "global::System.UInt128?[]" => GetNullableArrayReadCall(field, "UInt128"),
            "Int128?[]" or "global::System.Int128?[]" => GetNullableArrayReadCall(field, "Int128"),
            "bool?[]" or "global::System.Boolean?[]" => GetNullableArrayReadCall(field, "bool"),

            // Check if it's a OneOf<None, T> type where T is a known BcsStruct
            _ when IsOneOfNoneType(field.TypeSymbol, allTypes, out var innerTypeInfo) => GetOneOfFormatterReadCall(field, innerTypeInfo!),

            // Check if it's a tuple type
            _ when IsTupleType(fullyQualifiedTypeName, out var tupleTypes) => GetTupleReadCall(field, tupleTypes, allTypes),

            // Check if it's a known BcsStruct type - use dedicated formatter
            _ when allTypes.ContainsKey(GetFullyQualifiedTypeName(field.TypeSymbol)) => GetFormatterReadCall(field, allTypes[GetFullyQualifiedTypeName(field.TypeSymbol)]),

            // Fall back to BcsSerializer for unknown complex types
            _ => $"BcsSerializer.Deserialize<{fullyQualifiedTypeName}>(ref reader)"
        };
    }

    private static bool IsPrimitiveArrayType(string typeName)
    {
        return typeName switch
        {
            // Handle both simple and fully qualified names
            "bool[]" or "global::System.Boolean[]" or
            "byte[]" or "global::System.Byte[]" or
            "sbyte[]" or "global::System.SByte[]" or
            "ushort[]" or "global::System.UInt16[]" or
            "short[]" or "global::System.Int16[]" or
            "uint[]" or "global::System.UInt32[]" or
            "int[]" or "global::System.Int32[]" or
            "ulong[]" or "global::System.UInt64[]" or
            "long[]" or "global::System.Int64[]" or
            "UInt128[]" or "global::System.UInt128[]" or
            "Int128[]" or "global::System.Int128[]" or
            "global::Nethermind.Int256.UInt256[]" => true,
            _ => false
        };
    }

    private static bool IsNullableArrayType(string typeName)
    {
        return typeName switch
        {
            "byte?[]" or "global::System.Byte?[]" or
            "sbyte?[]" or "global::System.SByte?[]" or
            "ushort?[]" or "global::System.UInt16?[]" or
            "short?[]" or "global::System.Int16?[]" or
            "uint?[]" or "global::System.UInt32?[]" or
            "int?[]" or "global::System.Int32?[]" or
            "ulong?[]" or "global::System.UInt64?[]" or
            "long?[]" or "global::System.Int64?[]" or
            "UInt128?[]" or "global::System.UInt128?[]" or
            "Int128?[]" or "global::System.Int128?[]" or
            "bool?[]" or "global::System.Boolean?[]" => true,
            _ => false
        };
    }

    private static void GeneratePrimitiveArrayHelpers(StringBuilder sb)
    {
        sb.AppendLine("    // Helper methods for primitive arrays");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    private static T[] ReadPrimitiveArray<T>(ref BcsReader reader) where T : unmanaged");
        sb.AppendLine("    {");
        sb.AppendLine("        var length = (int)reader.ReadULEB32();");
        sb.AppendLine("        if (length == 0) return [];");
        sb.AppendLine("        ");
        sb.AppendLine("        var result = new T[length];");
        sb.AppendLine("        var byteSpan = System.Runtime.InteropServices.MemoryMarshal.AsBytes(result.AsSpan());");
        sb.AppendLine("        var readSpan = reader.ReadBytesAsSpan(byteSpan.Length);");
        sb.AppendLine("        readSpan.CopyTo(byteSpan);");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateNullableArrayHelpers(StringBuilder sb, List<BcsFieldInfo> nullableArrayFields)
    {
        sb.AppendLine("    // Helper methods for nullable arrays");

        // Get unique element types from the fields
        var elementTypes = nullableArrayFields
            .Select(f => GetFullyQualifiedTypeName(f.TypeSymbol).Replace("?[]", "").Replace("global::System.", "").Replace("global::", ""))
            .Distinct()
            .ToList();

        foreach (var elementType in elementTypes)
        {
            var readCall = GetNullableElementReadCall(elementType);

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    private static {elementType}?[] ReadNullableArray_{elementType}(ref BcsReader reader)");
            sb.AppendLine("    {");
            sb.AppendLine("        var length = (int)reader.ReadULEB32();");
            sb.AppendLine("        if (length == 0) return null;");
            sb.AppendLine($"        var array = new {elementType}?[length];");
            sb.AppendLine("        for (int i = 0; i < length; i++)");
            sb.AppendLine("        {");
            sb.AppendLine($"            array[i] = {readCall};");
            sb.AppendLine("        }");
            sb.AppendLine("        return array;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void GenerateEnumHelpers(StringBuilder sb, List<BcsFieldInfo> enumFields)
    {
        sb.AppendLine("    // Helper methods for C-style enum serialization (by ordinal position)");

        // Get unique enum types from the fields
        var enumTypes = enumFields
            .Select(f => new { TypeSymbol = f.TypeSymbol, TypeName = GetFullyQualifiedTypeName(f.TypeSymbol) })
            .GroupBy(x => x.TypeName)
            .Select(g => g.First())
            .ToList();

        foreach (var enumType in enumTypes)
        {
            var enumTypeName = enumType.TypeName;
            var suffix = GetEnumHelperSuffix(enumTypeName);

            if (enumType.TypeSymbol is not INamedTypeSymbol namedTypeSymbol)
                continue;

            // Get enum members in declaration order
            var enumMembers = namedTypeSymbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.HasConstantValue)
                .OrderBy(f => f.Locations.FirstOrDefault()?.SourceSpan.Start ?? 0)
                .ToList();

            // Generate static cached enum values array
            sb.AppendLine($"    private static readonly {enumTypeName}[] _enumValues_{suffix} = new {enumTypeName}[]");
            sb.AppendLine("    {");
            for (int i = 0; i < enumMembers.Count; i++)
            {
                var comma = i < enumMembers.Count - 1 ? "," : "";
                sb.AppendLine($"        {enumTypeName}.{enumMembers[i].Name}{comma}");
            }
            sb.AppendLine("    };");
            sb.AppendLine();

            // Generate write method
            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    private static void WriteEnumOrdinal_{suffix}(ref BcsWriter writer, {enumTypeName} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        // BCS C-style enum serialization: Use ordinal position (index) within enum definition");
            sb.AppendLine($"        var position = Array.IndexOf(_enumValues_{suffix}, value);");
            sb.AppendLine("        if (position == -1)");
            sb.AppendLine("        {");
            sb.AppendLine($"            throw new InvalidOperationException($\"Enum value {{value}} not found in {enumTypeName}\");");
            sb.AppendLine("        }");
            sb.AppendLine("        // Always serialize as byte representing the ordinal position");
            sb.AppendLine("        writer.Write((byte)position);");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate read method
            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    private static {enumTypeName} ReadEnumOrdinal_{suffix}(ref BcsReader reader)");
            sb.AppendLine("    {");
            sb.AppendLine($"        // BCS C-style enum deserialization: Read ordinal position and convert to enum value");
            sb.AppendLine("        var position = reader.Read8();");
            sb.AppendLine($"        if (position >= _enumValues_{suffix}.Length)");
            sb.AppendLine("        {");
            sb.AppendLine($"            throw new InvalidOperationException($\"Invalid enum position {{position}} for {enumTypeName}. Enum has {{_enumValues_{suffix}.Length}} values (0-{{_enumValues_{suffix}.Length - 1}})\");");
            sb.AppendLine("        }");
            sb.AppendLine($"        return _enumValues_{suffix}[position];");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void GenerateResolver(StringBuilder sb, ImmutableArray<BcsStructInfo> types)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using BcsSharp.Core;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine();
        sb.AppendLine("namespace BcsSharp.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated resolver that provides optimized formatters for [BcsStruct] types.");
        sb.AppendLine("/// This resolver should be used first in CompositeResolver for best performance.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class BcsSourceGeneratorResolver : IFormatterResolver");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly BcsSourceGeneratorResolver Instance = new();");
        sb.AppendLine("    private static readonly ConcurrentDictionary<Type, object?> _formatterCache = new();");
        sb.AppendLine();
        sb.AppendLine("    private BcsSourceGeneratorResolver() { }");
        sb.AppendLine();
        sb.AppendLine("    public IBcsFormatter<T>? GetFormatter<T>()");
        sb.AppendLine("    {");
        sb.AppendLine("        return (IBcsFormatter<T>?)_formatterCache.GetOrAdd(typeof(T), CreateFormatter);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static object? CreateFormatter(Type type)");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            var namespaceName = string.IsNullOrEmpty(type.Namespace) ? "BcsSharp.Generated" : $"{type.Namespace}.Generated";
            var formatterClassName = type.FullTypeName.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_') + "Formatter";
            sb.AppendLine($"        if (type == typeof({type.FullTypeName})) return {namespaceName}.{formatterClassName}.Instance;");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
