using System;
using System.IO;
using BcsSharp.Core;
using BcsSharp.Core.Types;
using Xunit;

namespace BcsSharp.Tests
{
    /// <summary>
    /// Byte-by-byte comparison tests between Rust and C# BCS serialization
    /// Reads binary files generated by Rust and compares them with C# output
    /// </summary>
    public class ByteByByteComparisonTests
    {
        private readonly string _rustFilesPath;

        public ByteByByteComparisonTests()
        {
            // Find solution directory by looking for .sln file
            var currentDir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (currentDir != null && !currentDir.GetFiles("*.sln").Any())
            {
                currentDir = currentDir.Parent;
            }
            
            if (currentDir == null)
                throw new DirectoryNotFoundException("Could not find solution directory");
                
            _rustFilesPath = Path.Combine(currentDir.Parent!.FullName, "rust-sui-bcs-test");
        }

        #region C# Struct Definitions (same as RustBcsCompatibilityTests)

        public enum AssetType : byte
        {
            Weapon = 0,
            Armor = 1,
            Consumable = 2,
            Material = 3,
            Currency = 4
        }

        public enum Rarity : byte
        {
            Common = 0,
            Uncommon = 1,
            Rare = 2,
            Epic = 3,
            Legendary = 4
        }

        public enum TransactionType : byte
        {
            Transfer = 0,
            Purchase = 1,
            Sale = 2,
            Mint = 3,
            Burn = 4
        }

        public class User
        {
            public ulong Id { get; set; }
            public string Name { get; set; } = string.Empty;
            public string Email { get; set; } = string.Empty;
            public ulong Balance { get; set; }
            public bool IsVerified { get; set; }
        }

        public class Attribute
        {
            public string Name { get; set; } = string.Empty;
            public uint Value { get; set; }
        }

        public class GameAsset
        {
            public string AssetId { get; set; } = string.Empty;
            public AssetType AssetType { get; set; }
            public Rarity Rarity { get; set; }
            public byte Level { get; set; }
            public Attribute[] Attributes { get; set; } = [];
        }

        public class Transaction
        {
            public string TxId { get; set; } = string.Empty;
            public ulong FromUser { get; set; }
            public ulong ToUser { get; set; }
            public ulong Amount { get; set; }
            public ulong Timestamp { get; set; }
            public TransactionType TxType { get; set; }
        }

        public class MarketplaceItem
        {
            public string ItemId { get; set; } = string.Empty;
            public ulong Seller { get; set; }
            public GameAsset Asset { get; set; } = new();
            public ulong Price { get; set; }
            public ulong ListedAt { get; set; }
            public bool IsActive { get; set; }
        }

        #endregion

        [Fact]
        public void ByteByByte_User_ShouldMatchRust()
        {
            // Arrange - same data as Rust
            var user = new User
            {
                Id = 12345,
                Name = "Alice",
                Email = "alice@example.com",
                Balance = 1000,
                IsVerified = true
            };

            // Act - serialize with C#
            var userType = BcsStruct.Create<User>();
            var csharpBytes = userType.Serialize(user);

            // Read Rust bytes
            var rustBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "user.bcs"));

            // Assert - byte-by-byte comparison

            Assert.Equal(rustBytes.Length, csharpBytes.Length);
            Assert.Equal(rustBytes, csharpBytes);
        }

        [Fact]
        public void ByteByByte_Transaction_ShouldMatchRust()
        {
            // Arrange - same data as Rust
            var transaction = new Transaction
            {
                TxId = "0x1234567890abcdef",
                FromUser = 12345,
                ToUser = 67890,
                Amount = 250,
                Timestamp = 1640995200,
                TxType = TransactionType.Transfer
            };

            // Act - serialize with C#
            var transactionType = BcsStruct.Create<Transaction>();
            var csharpBytes = transactionType.Serialize(transaction);

            // Read Rust bytes
            var rustBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "transaction.bcs"));

            // Assert - byte-by-byte comparison

            Assert.Equal(rustBytes.Length, csharpBytes.Length);
            Assert.Equal(rustBytes, csharpBytes);
        }

        [Fact]
        public void ByteByByte_GameAsset_ShouldMatchRust()
        {
            // Arrange - same data as Rust with nested arrays
            var asset = new GameAsset
            {
                AssetId = "sword_001",
                AssetType = AssetType.Weapon,
                Rarity = Rarity.Epic,
                Level = 15,
                Attributes = new[]
                {
                    new Attribute { Name = "damage", Value = 85 },
                    new Attribute { Name = "speed", Value = 12 }
                }
            };

            // Act - serialize with C#
            var assetType = BcsStruct.Create<GameAsset>();
            var csharpBytes = assetType.Serialize(asset);

            // Read Rust bytes
            var rustBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "asset.bcs"));

            // Assert - byte-by-byte comparison

            // Nested arrays are now fixed - enable assertions
            Assert.Equal(rustBytes.Length, csharpBytes.Length);
            Assert.Equal(rustBytes, csharpBytes);
        }

        [Fact]
        public void ByteByByte_MarketplaceItem_ShouldMatchRust()
        {
            // Arrange - same data as Rust with nested objects
            var asset = new GameAsset
            {
                AssetId = "sword_001",
                AssetType = AssetType.Weapon,
                Rarity = Rarity.Epic,
                Level = 15,
                Attributes = new[]
                {
                    new Attribute { Name = "damage", Value = 85 },
                    new Attribute { Name = "speed", Value = 12 }
                }
            };

            var marketplaceItem = new MarketplaceItem
            {
                ItemId = "market_001",
                Seller = 12345,
                Asset = asset,
                Price = 500,
                ListedAt = 1640995200,
                IsActive = true
            };

            // Act - serialize with C#
            var marketplaceType = BcsStruct.Create<MarketplaceItem>();
            var csharpBytes = marketplaceType.Serialize(marketplaceItem);

            // Read Rust bytes
            var rustBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "marketplace.bcs"));

            // Assert - byte-by-byte comparison

            // Nested objects are now fixed - enable assertions
            Assert.Equal(rustBytes.Length, csharpBytes.Length);
            Assert.Equal(rustBytes, csharpBytes);
        }

        [Fact]
        public void ByteByByte_ShowRustHexDumps()
        {
            // Verify all Rust binary files exist and are readable
            var userBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "user.bcs"));
            var assetBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "asset.bcs"));
            var transactionBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "transaction.bcs"));
            var marketplaceBytes = File.ReadAllBytes(Path.Combine(_rustFilesPath, "marketplace.bcs"));

            // Basic validation that files contain expected data
            Assert.True(userBytes.Length > 0);
            Assert.True(assetBytes.Length > 0);
            Assert.True(transactionBytes.Length > 0);
            Assert.True(marketplaceBytes.Length > 0);
        }
    }
}